### ISSUE TITLE
how to set socket path in cardano wallet ?

### ISSUE THREAD

**Issue by aliworkshop** [echovl/cardano-go#15]
hey every one
i charge my testnet address that generated by this package wallet  but when i call balance method i get 0 .
i guess that it's because of socket path that not set in variable 'CARDANO_NODE_SOCKET_PATH' 

how we should do that ?

**Comment by echovl** [comment]
If you're using bash you can set the socket path like this: 
```export CARDANO_NODE_SOCKET_PATH=/cardano/socket/path/```
