### ISSUE TITLE
Add multiasset support

### ISSUE THREAD

**Issue by echovl** [echovl/cardano-go#27]

**Comment by frogchocolatebarpie** [comment]
Any updates? I am also looking forward to supporting multiasset?

**Comment by echovl** [comment]
Should be ready by this week

**Comment by frogchocolatebarpie** [comment]
I see your commit to support multi assets. Thanks.
Is this Transfer function of Wallet finished? I see no argument "multiAsset" is this function.

**Comment by echovl** [comment]
Should be working rn, check it out and let me know if you find issues.

**Comment by frogchocolatebarpie** [comment]
Worked for me. Thanks
