### ISSUE TITLE
Deserialize not working for Amount.Inputs

### ISSUE THREAD

**Issue by frogchocolatebarpie** [echovl/cardano-go#30]
This unit test is setting transaction body inputs to empty https://github.com/echovl/cardano-go/blob/fd832fe8c7114cf9ea81b549b562bdfaab50aeb8/tx_test.go#L84? Any problem with serializing/deserializing for the map in cbor?

**Comment by visopsys** [comment]
@echovl any reason why you omit the Amount field in the TxInput struct?

https://github.com/echovl/cardano-go/blob/master/tx.go#L90

**Comment by echovl** [comment]
The serialized txInput doesn't contain the amount field, it's there only for the building process.

https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L69

**Comment by frogchocolatebarpie** [comment]
@echovl Thank you for your support! Keep going on bro.
