### ISSUE TITLE
Incorrect min amount for multiasset transaction

### ISSUE THREAD

**Issue by visopsys** [echovl/cardano-go#31]
I think this min value [calculation](https://github.com/echovl/cardano-go/blob/master/tx_builder.go#L118) for multiasset transaction is incorrect:

```
func (tb *TxBuilder) MinCoinsForTxOut(txOut *TxOutput) Coin {
	var size uint
	if txOut.Amount.OnlyCoin() {
		size = 1
	} else {
		numAssets := txOut.Amount.MultiAsset.numAssets()
		assetsLength := txOut.Amount.MultiAsset.assetsLength()
		numPIDs := txOut.Amount.MultiAsset.numPIDs()

		size = 6 + uint(math.Floor(
			float64(numAssets*12+assetsLength+numPIDs*28+7)/8,
		))
	}
	return Coin(utxoEntrySizeWithoutVal+size) * tb.protocol.CoinsPerUTXOWord
}

```

I have a multi-asset input and my values are as follow:
```
numAssets = 1, assetsLength = 8, numPIDs = 1, utxoEntrySizeWithoutVal = 27, tb.protocol.CoinsPerUTXOWord
 = 4310
```

Total coin amount = 168090 (or 0.16809 ADA)

This number is clearly smaller than min 1.3 ADA required to transfer multiasset. I got `BabbageOutputTooSmallUTxO` error when submitting this. Please check this function again for multi-asset

**Comment by visopsys** [comment]
How do you come up with the calculation formula?

**Comment by core-dev-crypto** [comment]
Hi @echovl,

I'll check the general formula and it seem corret. I think that the error is in the rounding of `size` calculation:

`
size = 6 + uint(math.Floor(
			float64(numAssets*12+assetsLength+numPIDs*28+7)/8,
		))
`

The `+7` is used in case of truncation to flooring the number. So 

`
size = 6 + uint(math.Trunc(
			float64(numAssets*12+assetsLength+numPIDs*28+7)/8,
		))
`

or

`
size = 6 + uint(math.Floor(
			float64(numAssets*12+assetsLength+numPIDs*28)/8,
		))
`

are the possible solutions.

**Comment by echovl** [comment]
@core-dev-crypto can u make a PR?, I'm really busy these days, will check it out later
